/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <blue2.h>
#include <R2_aliases.h>
#include <R2.h>
#include <red2.h>
#include <green2.h>
#include <red.h>
#include <R1_aliases.h>
#include <R1.h>
#include <G1_aliases.h>
#include <G1.h>
#include <B1_aliases.h>
#include <B1.h>
#include <A_aliases.h>
#include <A.h>
#include <B_aliases.h>
#include <B.h>
#include <C_aliases.h>
#include <C.h>
#include <clock_aliases.h>
#include <clock.h>
#include <LAT_aliases.h>
#include <LAT.h>
#include <clk.h>
#include <OEpin_aliases.h>
#include <OEpin.h>
#include <CBA.h>
#include <Latch.h>
#include <OE.h>
#include <blue.h>
#include <green.h>
#include <Timer_1.h>
#include <isr_1.h>
#include <G2_aliases.h>
#include <G2.h>
#include <B2_aliases.h>
#include <B2.h>
#include <USBUART_1.h>
#include <USBUART_1_audio.h>
#include <USBUART_1_cdc.h>
#include <USBUART_1_hid.h>
#include <USBUART_1_midi.h>
#include <USBUART_1_pvt.h>
#include <LCD_Char.h>
#include <UART_1.h>
#include <emFile_1.h>
#include <isr_Tx.h>
#include <isr_Rx.h>
#include <USBUART_1_ep3_dma.h>
#include <USBUART_1_ep2_dma.h>
#include <USBUART_1_ep1_dma.h>
#include <USBUART_1_Dm_aliases.h>
#include <USBUART_1_Dm.h>
#include <USBUART_1_Dp_aliases.h>
#include <USBUART_1_Dp.h>
#include <LCD_Char_LCDPort_aliases.h>
#include <LCD_Char_LCDPort.h>
#include <UART_1_IntClock.h>
#include <emFile_1_SPI0.h>
#include <emFile_1_SPI0_PVT.h>
#include <emFile_1_mosi0_aliases.h>
#include <emFile_1_mosi0.h>
#include <emFile_1_Clock_1.h>
#include <emFile_1_miso0_aliases.h>
#include <emFile_1_miso0.h>
#include <emFile_1_sclk0_aliases.h>
#include <emFile_1_sclk0.h>
#include <emFile_1_SPI0_CS_aliases.h>
#include <emFile_1_SPI0_CS.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

